### ISSUE TITLE
Hide compiler-specific code in a new header

### ISSUE THREAD

**Issue by mmdriley** [google/safeside#20]
For example, we sometimes need `noline` or `always_inline` and those are different across compilers. We should have a macro like `SAFESIDE_NOINLINE` that hides that complexity and shares a definition across different programs.

Inspiration from https://github.com/abseil/abseil-cpp/blob/master/absl/base/attributes.h and https://cs.chromium.org/chromium/src/v8/include/v8config.h

**Comment by asteinha** [comment]
What name of the header file do you want? directives.h?

**Comment by mmdriley** [comment]
Up to you. Something descriptive like `compiler_support.h` or `compiler_specifics.h` could be okay.
