### ISSUE TITLE
Build demos with CMake

### ISSUE THREAD

**Issue by mmdriley** [google/safeside#5]
This might include moving some code around to better segment "library" code from the entrypoint programs.

**Comment by itzurabhi** [comment]
if this is not taken, I would like to work on this.

**Comment by ssbr** [comment]
By all means! That's really nice of you to offer. Please let any of us know (either here or on the mailing list) if you're having trouble -- although if I'm honest we aren't necessarily that experienced with CMake since we come from the land of Bazel.

**Comment by asteinha** [comment]
The only known issue is that MSVC must use Release builds, not Debug builds.
