### ISSUE TITLE
Fix arm64 and ppc64le tests on Travis

### ISSUE THREAD

**Issue by mmdriley** [google/safeside#99]
Our `spectre_v1_btb_sa` test doesn't currently succeed on Travis' arm64 or ppc64le workers. We should figure out why, fix them, and re-enable the tests in `.travis.yml`.

**Comment by asteinha** [comment]
PowerPC failure is expected, since it has the BTB disabled by firmware. ARM64 is a flake and it might be because of the imprecise time measurement. I would start with Spectre v1 PHT SA or Spectre v4. Those should run everywhere.

**Comment by mmdriley** [comment]
Ack, yes, absolutely right. I wasn't paying close enough attention to the test name. Thanks!
